name: bard_api
description: Reverse engineering of Google's Bard chatbot API.
version: 1.0.0
repository: https://github.com/jctaoo/bard_api

environment:
  sdk: ">=2.19.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
